version: '2'
services:
  nginx:
    build: ./nginx
    networks:
      - backend
      - frontend
    ports:
      - "80:80"
    links:
      - web
    depends_on:
      - web
    environment:
      WEB_HOST: web
    volumes_from:
      - web
  postgres:
      image: postgres
      environment:
        - POSTGRES_USER=testuser
        - POSTGRES_PASSWORD=test@PaSS_W0rD
        - POSTGRES_DB=test
      volumes:
        - ./postgres:/docker-entrypoint-initdb.d:ro
        - ./postgres_db:/var/lib/postgresql/data:rw
      networks:
        - backend
      ports:
        - "5432:5432"
  web:
    build: .
    working_dir: /opt/test # <- Recommend to change this line
    command: bash -c "uwsgi --ini uwsgi.ini --http :8000"
    environment:
      - POSTGRES_HOST=postgres
    ports:
      - "8000:8000"
    networks:
      - frontend
      - backend
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - IS_HTTPS_IN_FRONT_OF_NGINX=False
    links:
      - postgres
    volumes:
      - /opt/test/collected_static # <-Recommend to change this line
networks:
  frontend: # exposed
  backend: # not exposed
